parameters:
    auth:
        url: '%env(resolve:AUTHAPI_HOST)%'
        client_id: '%env(resolve:AUTHAPI_CLIENT_ID)%'
        client_secret: '%env(resolve:AUTHAPI_CLIENT_SECRET)%'

services:
    RemoteTech\ComAxe\Client\Oauth\AuthAuthenticator:
        class: RemoteTech\ComAxe\Client\Oauth\AuthAuthenticator
        arguments:
            $authService: '@RemoteTech\ComAxe\Client\Oauth\AuthService'
            $router: '@router.default'

    RemoteTech\ComAxe\Client\Oauth\AuthService:
        class: RemoteTech\ComAxe\Client\Oauth\AuthService
        arguments:
            $config: '%auth%'
            $requestStack: '@request_stack'
            $userProvider:   '@RemoteTech\ComAxe\Client\Oauth\UserProvider\AxeUserProviderInterface'
            $logger: ~

    RemoteTech\ComAxe\Client\Oauth\AuthUserProvider:
        class: RemoteTech\ComAxe\Client\Oauth\AuthUserProvider
        arguments:
            $authService: '@RemoteTech\ComAxe\Client\Oauth\AuthService'
            $logger: ~

    RemoteTech\ComAxe\Client\Oauth\LoginSuccessEventListener:
        tags: [ 'kernel.event_subscriber' ]

    # configure the user provider
    RemoteTech\ComAxe\Client\Oauth\UserProvider\AxeUserProviderInterface:
        alias: RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine
    
    # doctrine services & config
    RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine:
        class: RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine
        arguments:
            $managerRegistry: '@doctrine'

doctrine:
    orm:
        mappings:
            Oauth:
                is_bundle: false
                dir: '%kernel.project_dir%/vendor/remote-tech/com.axe.client/src/Oauth/Model'
                prefix: 'RemoteTech\ComAxe\Client\Oauth\Model'
                alias: Oauth