parameters:
    auth:
        url: '%env(resolve:AUTHAPI_HOST)%'
        client_id: '%env(resolve:AUTHAPI_CLIENT_ID)%'
        client_secret: '%env(resolve:AUTHAPI_CLIENT_SECRET)%'

services:
    rt_authenticator:
        class: RemoteTech\ComAxe\Client\Oauth\AuthAuthenticator
        arguments:
            $authService: '@rt_auth_service'
            $router: '@router.default'

    rt_auth_service:
        class: RemoteTech\ComAxe\Client\Oauth\AuthService
        arguments:
            $config: '%auth%'
            $requestStack: '@request_stack'
            $userProvider:   '@RemoteTech\ComAxe\Client\Oauth\UserProvider\AxeUserProviderInterface'
            $logger: ~

    rt_user_provider:
        class: RemoteTech\ComAxe\Client\Oauth\AuthUserProvider
        arguments:
            $authService: '@rt_auth_service'
            $logger: ~

    # configure the user provider
    RemoteTech\ComAxe\Client\Oauth\UserProvider\AxeUserProviderInterface:
        alias: RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine

#### - remove the following if you want to use a custom user provider

    # doctrine services & config
    RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine:
        class: RemoteTech\ComAxe\Client\Oauth\UserProvider\Doctrine
        arguments:
            $managerRegistry: '@doctrine'

doctrine:
    orm:
        mappings:
            Oauth:
                is_bundle: false
                dir: '%kernel.project_dir%/vendor/remote-tech/com.axe.client/src/Oauth/Model'
                prefix: 'RemoteTech\ComAxe\Client\Oauth\Model'
                alias: Oauth